apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oligo-apikey-es
  namespace: oligo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: oligo-apikey
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: oligo/gateway      # Vault KV path: secret/data/oligo/gateway
        property: apikey
