apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: oligo-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      server: "http://vault-app.vault.svc.cluster.local" # TODO: Replace with your Vault address
      path: "secret"                       # KV v2 mount path
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "oligo-external-secrets"    # TODO: Replace with your Vault K8s auth role
          serviceAccountRef:
            name: "oligo-operator"         # SA that ESO uses to authenticate to Vault
