imagePullSecret:
  username: "oligocustomer"
  password: "REDACTED_DOCKER_PAT"
  name: oligoregcred
controllerManager:
  clientId: "ec63c360-88d1-4442-8eaa-6c66eb946119"
  clusterName: "k3d-thuan-k3d"
  gateway:
    pollerEnabled: true
    apiVersion: v2
    pollerInterval: 5m
    url: https://gateway.oligo.security
    apiKey: "REDACTED_API_KEY"
  manager:
    image:
      repository: oligosecurity/operator
fluent-bit:
  enabled: true
sensorOverrides:
  sensor:
    featureSystemWideProgramEvents:
      enabled: true
