apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scanner.serviceAccountName" . }}
  labels:
    {{- include "oligo-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scanner.clusterRoleName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods
  - namespaces
  - nodes
  - services
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scanner.clusterRoleBindingName" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "scanner.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "scanner.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
