apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oligo-operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
  {{- include "oligo-operator.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}