apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sensor.serviceAccountName" . }}
  labels:
    {{- include "oligo-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sensor.clusterRoleName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sensor.clusterRoleBindingName" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "sensor.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "sensor.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
