{{ if not (eq .Values.controllerManager.gateway.apiKey "") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.controllerManager.gateway.apiKeySecretName }}"
  labels:
  {{- include "oligo-operator.labels" . | nindent 4 }}
type: Opaque
data:
  apikey: {{ .Values.controllerManager.gateway.apiKey | b64enc }}
{{ end }}