{{- if and .Values.imagePullSecret.required .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "oligo-operator.imagePullSecretName" . }}
  labels:
    {{- include "oligo-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "oligo-operator.imagePullSecretValue" . }}
{{- end -}}
